### ISSUE TITLE
provide timing results

### ISSUE THREAD

**Issue by Beliavsky** [jalvesz/fast_math#1]
Could you provide some timing results, comparing your functions with compiler intrinsics? That would encourage people to try out your project.

**Comment by jalvesz** [comment]
Done, they are reported in the readme file for different compilers.

**Comment by Beliavsky** [comment]
I see a section "Elapsed time examples and precision" with compiler options but not the actual times.

**Comment by jalvesz** [comment]
The small arrows are expandable sections, click on each line with the compiler options and you'll see the times.
